apiVersion: platform-ops/v1
kind: Release

metadata:
  application: vantry
  environment: production

release:
  version: "1.3.0"
  sourceCommit: "eed836d61dfdebbe6c96231d8a9ebd844fe530b8"
  createdAt: "2026-09-07T20:41:20Z"

components:
  backend:
    image: ghcr.io/chicaomsc/contractor-platform-backend
    tag: "1.3.0"
    digest: "sha256:b6006b8a928b3c627a690cff2882494963f6f678264ee166d885de73f86cd593"
  frontend:
    image: ghcr.io/chicaomsc/contractor-platform-frontend
    tag: "1.3.0"
    digest: "sha256:805015a64ab91715a2687d502914f6db0e361a3f9344c3ed7c0f7e951e49abd5"
  caddy:
    image: ghcr.io/chicaomsc/contractor-platform-caddy
    tag: "1.3.0"
    digest: "sha256:dfe7e758ae0f20e470e6a3e9d6e70f2c5b9e533e92b70df0f62036ddff71e802"
