apiVersion: platform-ops/v1
kind: Release

metadata:
  application: vantry
  environment: production

release:
  version: "1.5.0"
  sourceCommit: "264d86f32b151e9992cff1069d6067c91f863845"
  createdAt: "2026-09-10T00:22:00Z"

components:
  backend:
    image: ghcr.io/chicaomsc/contractor-platform-backend
    tag: "1.5.0"
    digest: "sha256:5459619088472dcee31d257c24df35cbcd5a98829432fd81c08d518e19f2fe24"
  frontend:
    image: ghcr.io/chicaomsc/contractor-platform-frontend
    tag: "1.5.0"
    digest: "sha256:5a5659107c2a185850d95bbec2ed219e2fa5f6f6fae88ac07bd59134850dfd92"
  caddy:
    image: ghcr.io/chicaomsc/contractor-platform-caddy
    tag: "1.5.0"
    digest: "sha256:a4c95d4213f70decef8c40de9e03aefc4381880e5f2201cfbd21d52325207a11"
