apiVersion: platform-ops/v1
kind: Release

metadata:
  application: vantry
  environment: production

release:
  version: "1.4.0"
  sourceCommit: "ed7c1d3b15320f51b7e53292b446982aa05eb2e2"
  createdAt: "2026-09-09T14:24:13Z"

components:
  backend:
    image: ghcr.io/chicaomsc/contractor-platform-backend
    tag: "1.4.0"
    digest: "sha256:cd749c7fd523d7ddc927af55d479a1728d894fef08c3c2e7fd3f75d9c4369bea"
  frontend:
    image: ghcr.io/chicaomsc/contractor-platform-frontend
    tag: "1.4.0"
    digest: "sha256:ac0979527284219ca4a3daa765f2802d7132a4e847e9b63b781d4e49b4fd9945"
  caddy:
    image: ghcr.io/chicaomsc/contractor-platform-caddy
    tag: "1.4.0"
    digest: "sha256:e403b27429258464c374641f180b533ee82786b8ac7ef2fef16b31c659fc2e80"
